steps:

- checkout: self
  submodules: true

- script: |
    echo '##vso[task.prependpath]$(CARGO_HOME)/bin'
    echo '##vso[task.prependpath]$(HOME)/.cargo/bin'

- script: |
    bash -c "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable"
  displayName: 'Install rustc'

- script: python ./tools/setup.py
  displayName: 'setup'

#- script: |
#    echo is_asan=true >> target/debug/args.gn
#    echo is_lsan=true >> target/debug/args.gn

- script: python ./tools/build.py
  displayName: 'build'

- script: python ./tools/test.py
  displayName: 'test'
