# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  CARGO_HOME: '$(system.defaultWorkingDirectory)/third_party/rust_crates/'
  PREBUILT: '$(system.defaultWorkingDirectory)/prebuilt/'
  RUST_BACKTRACE: 1
  RUSTC_WRAPPER: sccache
  SCCACHE_BUCKET: deno-sccache
  AWS_ACCESS_KEY_ID: AKIAIPOYFUDOPCMWRVZA
  # AWS_SECRET_ACCESS_KEY=...

jobs:

- job: 'Linux'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: echo '##vso[task.prependpath]$(PREBUILT)/linux64/'
  - template: azure-pipelines-steps.yml

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo '##vso[task.prependpath]$(PREBUILT)/win/'
  - template: azure-pipelines-steps.yml

- job: 'Mac'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo '##vso[task.prependpath]$(PREBUILT)/mac/'
  - template: azure-pipelines-steps.yml
