# This is an imagined crate directory structure for Deno ops.
# Same as op_hello but done with JS and not TS.

[package]
name = "op_hello_js"
version = "0.1.0"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"

# Note: I am explicitly attempting to not have a build.rs file. I think it might
# be unnecessary for each op crate to implement their own. Then again, it might
# be unavoidable... Let's try without first.

[dependencies]
deno = "0.19.0"
