[package]
name = "op_hello"
version = "0.1.0"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"

[dependencies]
deno = "0.19.0"
deno_std = "0.19.0" # TODO deno_std is not yet published as crate

