[package]
name = "op_hello"
version = "0.1.0"
authors = ["Ryan Dahl <ry@tinyclouds.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno = "0.19.0"

[dev-dependencies]
deno_typescript = "0.19.0"
