name: Benchmark updating

on: [push]

jobs:
  update_benchmark:
    name: Update benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: git config --global core.symlinks true

      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Environment
        run: |
          echo ::set-env name=RUSTC_WRAPPER::sccache
          echo ::set-env name=DENO_BUILD_MODE::release
          echo ::add-path::`pwd`/prebuilt/linux64

      - name: Run setup.py
        run: python ./tools/setup.py

      - name: Start sccache
        env:
          AWS_ACCESS_KEY_ID: AKIAIVRN52PLDBP55LBQ
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SCCACHE_BUCKET: deno-sccache
          SCCACHE_IDLE_TIMEOUT: 0
        run: sccache --start-server

      - name: Build
        run: cargo build -vv --release --locked --all-targets

      - name: Run benchmarks
        run: ./tools/benchmark.py

      - name: Copy benchmarks
        run: cp -r website/* gh-pages/

      # Upload benchmarks
      - name: Compress benchmarks
        run: zip gh-pages.zip gh-pages/**
      - name: Upload benchmarks as artifact
        uses: actions/upload-artifact@master
        with:
          name: benchmarks
          path: gh-pages.zip

      # Push to pages
      - name: Push to pages
        if: (github.ref == 'master' || github.ref == 'github-ci')
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd gh-pages
          git add .
          git commit --message "Update benchmarks"
          git push origin gh-pages
          curl -XPOST -H 'Accept: application/vnd.github.mister-fantastic-preview+json' -H 'Authorization: token $GH_PAT' 'https://api.github.com/repos/$GITHUB_REPOSITORY/pages/builds/latest'
