name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: git submodule update --init --recursive --depth=1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: ./tools/test.py
